### ISSUE TITLE
Create a v10.0 version of docs.

### ISSUE THREAD

**Issue by cristianoc** [rescript-association/rescript-lang.org#552]
Here are the verbatim release notes: for each item, need to evaluate whether some doc update is required.

# 10.0.1

#### :bug: Bug Fix

- [x]  Fix issue where watch mode would give an error on Windows https://github.com/rescript-lang/rescript-compiler/pull/5621

# 10.0.0

**Compiler**

#### :boom: Breaking Change

- [x] `bsconfig.json` does not support `// line` comments anymore.
  - Example: `"suffix": ".bs.js" // determine the suffix`
  - Fix: remove the comment and use standard json.
- [x] Changed return type of `Js.String.match_` as it was wrong. [#5070](https://github.com/rescript-lang/rescript-compiler/pull/5070)
  - Example: any use of `Js.String.match_` and `Js.String2.match_`
  - Fix: follow the type errors

#### :rocket: New Feature

- [x] New records with optional fields e.g. `type opt = {x: int, y?: string}` were added as an experimental feature [#5423](https://github.com/rescript-lang/rescript-compiler/pull/5423) [#5452](https://github.com/rescript-lang/rescript-compiler/issues/5452) [New Syntax](https://github.com/rescript-lang/syntax/pull/589/files)
- [x] Add support for `@new @variadic` (see https://github.com/rescript-lang/rescript-compiler/pull/5364)

#### :bug: Bug Fix

- [x] Classify bigint correctly [#5351](https://github.com/rescript-lang/rescript-compiler/pull/5351)
- [x] Fixed crash in `rescript build` on Windows [#5516](https://github.com/rescript-lang/rescript-compiler/pull/5516)
- [x] Fixed `rescript init` command not working [#5526](https://github.com/rescript-lang/rescript-compiler/pull/5526)
- [x] Fix issue with compiler log not terminated that causes problems with editor extension not clearing issues when fixed [#5545](https://github.com/rescript-lang/rescript-compiler/issues/5545)

##### :nail_care: Polish

- [x] Changed Linux build to depend on GLIBC 2.28 again for compatibility with Debian 10.

- [x] Proper M1 support (CI now supports M1 native builds)

**Syntax**

#### :boom: Breaking Change

- [x] `@bs.send.pipe` is now removed. Earlier it was deprecated.
- [x] Missing labels in function application is now an error (https://forum.rescript-lang.org/t/ann-more-strict-checks-in-missed-labels/2117).
  - Example: `let f = (x, ~z) => x + z; f(1, 2)`
  - Fix: do `let f = (x, ~z) => x + z; f(1, ~z=2)` instead
- [x] Externals without `@val` annotations do not work anymore, and externals with `= ""` give an error.
  - Example: `external setTimeout: (unit => unit, int) => float = "setTimeout"` is not supported anymore.
  - Fix: use `@val external setTimeout: (unit => unit, int) => float = "setTimeout"` instead.
  - Example2: `@val external setTimeout: (unit => unit, int) => float = ""` is not supported anymore.
  - Fix2: use `@val external setTimeout: (unit => unit, int) => float = "setTimeout"` instead.
- [x] Strings processed at compile-time don't need escaping anymore.
  - Example: `let blockCommentsRe = %re("/\\/\\*([^*]|[\\r\\n]|(\\*+([^*/]|[\\r\\n])))*\\*+\\//g")`.
  - Fix: use `let blockCommentsRe = %re("/\/\*([^*]|[\r\n]|(\*+([^*/]|[\r\n])))*\*+\//g")` instead.
- [x] Remove parsing of "import" and "export" which was never officially supported https://github.com/rescript-lang/syntax/pull/597 https://github.com/rescript-lang/syntax/pull/599
  - Example: `export type t = int`
  - Fix: `@genType type t = int`
  - Example2: `import realValue: complexNumber => float from "./MyMath"`
  - Fix2: `@genType.import("./MyMath") external realValue: complexNumber => float = "realValue"`

#### :rocket: New Feature

- [x] Unicode is now supported in regular strings and chars (when the symbol fits). This is now going to work: `let str = "Σ"`. And, you'll be able to pattern match on unicode chars: `switch c { | 'Σ' => "what a fine unicode char" | _ => "unicode is fun" }`
- [x] Doc comments `/** ... */` are now supported. Inernally, they are attributes, so are only valid at positions where `@foo` is allowed, or a syntax error is given. Similarly for module-level `/*** comments */` that can go where `@@attributes` go.

#### :bug: Bug Fix

- [x] Fix printing for inline nullary functor types [#477](https://github.com/rescript-lang/syntax/pull/477)
- [x] Fix stripping of quotes for empty poly variants [#474](https://github.com/rescript-lang/syntax/pull/474)
- [x] Implement syntax for arity zero vs arity one in uncurried application in [#139](https://github.com/rescript-lang/syntax/pull/139)
- [x] Fix parsing of first class module exprs as part of binary/ternary expr in [#256](https://github.com/rescript-lang/syntax/pull/256)
- [x] Fix formatter hanging on deeply nested function calls [#261](https://github.com/rescript-lang/syntax/issues/261)

**Libraries**

#### :boom: Breaking Change

- [x] **"Attributes not allowed here"**. If you see this error chances are you're using a ppx that needs updating to a new version.
  See an exampe of how to [update a ppx](https://github.com/zth/rescript-relay/pull/372)
  - Example: for `rescript-relay` 0.23.0 is not supported.
  - Fix: use `rescript-relay@beta` or the new version when released.
- [x] Removed printing modules (Printf, Format etc) and related functions. Details of files added/removed: https://github.com/rescript-lang/rescript-compiler/commit/0fd8bb0e77c4b0e96a9647ac8af614305057003f.

#### :bug: Bug Fix

- [x] Fix library issue with missing `bytes_to_string` https://github.com/rescript-lang/rescript-compiler/issues/5573 https://github.com/rescript-lang/rescript-compiler/pull/5589

#### :nail_care: Polish

- [x] Several Belt / Js libraries are now converted to ReScript syntax, with corresponding comments in Markdown format suitable for hovering. See [#5361](https://github.com/rescript-lang/rescript-compiler/pull/5361).

**Playground**

#### :house: Internal

- [x] Added `jsoo_playground_main.ml` as the rescript-lang.org playground bundle entrypoint

#### :boom: Breaking Change

- [x] Removed Reason syntax support for the playground experience. See https://github.com/rescript-lang/rescript-compiler/pull/5375

**Comment by zth** [comment]
I'll tackle optional record fields. WIP PR coming soon.
