### ISSUE TITLE
Create v10.1 docs

### ISSUE THREAD

**Issue by cristianoc** [rescript-association/rescript-lang.org#568]
Here are the verbatim release notes as of Nov 4: for each item, need to evaluate whether some doc update is required.
Ticked means: either not necessary, or doc updated.

# 10.1.0-rc.4

#### :rocket: New Feature

- [x] Support format check with `rescript format -check`. https://github.com/rescript-lang/rescript-compiler/pull/5760

#### :bug: Bug Fix

- [x] Fix issue where the last line of `rescript format --help` usage was being swallowed https://github.com/rescript-lang/rescript-compiler/pull/5760
- [x] Specialize the printing of the rhs of a record field assignment for optional values `{x: ? e}` https://github.com/rescript-lang/syntax/issues/714

# 10.1.0-rc.3

#### :rocket: New Feature

- [x] Support the use of spread anywhere in list creation (e.g. `list{...x, 1, ...y, ...z}). https://github.com/rescript-lang/syntax/pull/692 Docs: https://github.com/rescript-association/rescript-lang.org/pull/598

- [x] Add support for the argument of `@react.component` to set a props type from the outside. https://github.com/rescript-lang/syntax/pull/699

#### :bug: Bug Fix

- [x] Fix issue where the JSX key type is not an optional string https://github.com/rescript-lang/syntax/pull/693
- [x] Prevent inlining of async functions https://github.com/rescript-lang/rescript-compiler/issues/5754
- [x] Fix build error for JSX fragment without children https://github.com/rescript-lang/syntax/pull/704
- [x] Fix issue where async as an id cannot be used with application and labelled arguments https://github.com/rescript-lang/syntax/issues/707
- [x] Fix 5557: the exhaustive checking for char is incorrect during the unicode migration https://github.com/rescript-lang/rescript-compiler/pull/5749
- [x] Fix 5753: the comment for unicode char is inaccurate https://github.com/rescript-lang/syntax/pull/709
- [x] Treat await as almost-unary operator weaker than pipe so `await foo->bar` means `await (foo->bar)` https://github.com/rescript-lang/syntax/pull/711

#### :nail_care: Polish

- [x] Change payload of `Pconst_char` from `char` to `int` https://github.com/rescript-lang/syntax/pull/709
# 10.1.0-rc.2

#### :bug: Bug Fix

- [x] Fix issue with changes not being applied with React Native's Metro bundler for files with warnings https://github.com/rescript-lang/rescript-compiler/pull/5738
- [x] Fix emitting unary minus for floats in case of negative constants https://github.com/rescript-lang/rescript-compiler/pull/5737
- [x] Fix issue where a spread `...x` in non-last position would not be reported as syntax error https://github.com/rescript-lang/syntax/pull/673/
- [x] Fix issue where the formatter would delete `async` in a function with labelled arguments.
- [x] Fix several printing issues with `async` including an infinite loop https://github.com/rescript-lang/syntax/pull/680
- [x] Fix issue where certain JSX expressions would be formatted differenctly in compiler 10.1.0-rc.1 https://github.com/rescript-lang/syntax/issues/675
- [x] Fix issue where printing nested pipe discards await https://github.com/rescript-lang/syntax/issues/687

# 10.1.0-rc.1

#### :boom: Breaking Change

- [x] Deprecate DOM element attributes in `JsxDOM.domProps`: `begin_`, `end_`, `to_`
  - Use `begin`, `end`, `to` instead.
- [x] Emit an error when a `@string` or `@int` attribute is used in a V4 component https://github.com/rescript-lang/rescript-compiler/issues/5724

## :rocket: New Feature

- [x] Add extra variants for output filename suffixes in `bsconfig.json`: `.bs.mjs` and `.bs.cjs` are allowed https://github.com/rescript-lang/rescript-compiler/pull/5631
- [x] Safe promises: t-first Js.Promise2 bindings, and remove warning for nested promises https://github.com/rescript-lang/rescript-compiler/pull/5709

#### :bug: Bug Fix

- [x] Fix issue where uncurried async functions were emitted without `async` https://github.com/rescript-lang/rescript-compiler/pull/5718
- [x] Fix location issue in error messages with JSX V4 where the multiple props types are defined https://github.com/rescript-lang/syntax/pull/655
- [x] Fix location issue in make function in JSX V4 that breaks dead code elimination https://github.com/rescript-lang/syntax/pull/660
- [x] Fix parsing (hence pretty printing) of expressions with underscore `_` and comments.
- [x] Fix printing of comments inside JSX tag https://github.com/rescript-lang/syntax/pull/664
- [x] Fix issue where formatter erases tail comments inside JSX tag https://github.com/rescript-lang/syntax/issues/663
- [x] Fix issue where the JSX prop has type annotation of the first class module https://github.com/rescript-lang/syntax/pull/666
- [x] Fix issue where an empty record literal {} expected to have a non-record type would type check https://github.com/rescript-lang/rescript-compiler/pull/5729

#### :eyeglasses: Spec Compliance

- [x] Functions with consecutive dots now print as multiple arrow functions like in JavaScript.

#### :nail_care: Polish

- [x] Add `loading`, `aria-*` DOM element attributes in `JsxDOM.domProps`: `ariaCurrent`, `ariaInvalid`, `ariaAutocomplete`, etc.
- [x] Change the internal representation of props for the lowercase components to record. https://github.com/rescript-lang/syntax/pull/665

# 10.1.0-alpha.2

#### :rocket: New Feature

- [x] Fix pretty printer where it would print doc comments on the same line as other attributes https://github.com/rescript-lang/syntax/pull/642
- [x] Propagte `"jsx"` configuration to dependencies https://github.com/rescript-lang/rescript-compiler/pull/5661
- [x] Add support for empty record literal `{}` for records where all fields are optional https://github.com/rescript-lang/rescript-compiler/pull/5658
- [x] Add support for empty record type (e.g. `type empty = {}`) https://github.com/rescript-lang/rescript-compiler/pull/5658

#### :bug: Bug Fix

- [x] Fix issue in formatting JSX spread props https://github.com/rescript-lang/syntax/pull/644
- [x] Fix location issue in error messages with JSX V4 where the body of the component is an application https://github.com/rescript-lang/syntax/pull/633
- [x] Fix printing of type declarations in error message where they would be considered recursive by default
- [x] Fix issue where the printer would omit attributes for `->` and `|>` https://github.com/rescript-lang/syntax/pull/629
- [x] Fix printing of optional fields in records https://github.com/rescript-lang/rescript-compiler/issues/5654

#### :nail_care: Polish

- [x] Improvements and fixes for JSX V4. See guide https://github.com/rescript-lang/syntax/blob/master/cli/JSXV4.md
- [x] Mention all missing fields in error message for records, not just one https://github.com/rescript-lang/rescript-compiler/pull/5657

# 10.1.0-alpha.1

#### :boom: Breaking Change

- [x] Vendor genType, which does not need to be installed separately anymore. **Only TypeScript back-end** supported. https://github.com/rescript-association/rescript-lang.org/pull/597
- [x] Pipe `->` does not support a code block on the right-hand side e.g. `x->{ open A; get("test") }`

#### :rocket: New Feature

- [x] Experimental support for for `async`/`await` https://github.com/rescript-lang/rescript-compiler/pull/5537 DOC:https://github.com/rescript-association/rescript-lang.org/pull/590

- [x] Make `promise` a built-in type https://github.com/rescript-lang/rescript-compiler/pull/5650

- [x] JSX V4. https://github.com/rescript-association/rescript-lang.org/pull/593

- [x] Add placeholder types for ES6 collections: `Set`, `Map`, `WeakSet`, and `WeakMap` https://github.com/rescript-lang/rescript-compiler/pull/5630

#### :bug: Bug Fix

- [x] Fix issue with arrays and creation of recursive values https://github.com/rescript-lang/rescript-compiler/pull/5640
- [x] Fix issue where characters such as newlines would be escaped in a template string expression https://github.com/rescript-lang/rescript-compiler/issues/5638
- [x] Fix issue where pipe `->` processing eats up attributes https://github.com/rescript-lang/rescript-compiler/pull/5581
- [x] Fix issue where cancelling `rescript build` would leave the `.bsb.lock` file behind and block future builds

#### :nail_care: Polish

- [x] Print patterns in warnings using rescript printer https://github.com/rescript-lang/rescript-compiler/pull/5492
